import express from 'express';
import cors from 'cors';
import dotenv from 'dotenv';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import { User, connectDatabase } from './store.js';
dotenv.config();
const app = express(); app.use(cors({ origin: process.env.CLIENT_ORIGIN || true })); app.use(express.json());
const signUser = user => jwt.sign({ id: user._id, email: user.email }, process.env.JWT_SECRET || 'development-only-secret', { expiresIn: '7d' });
const careers = [
  { title:'Data Analyst', skills:['sql','excel','python','statistics','power bi'], why:'You enjoy finding patterns and communicating useful insights.' },
  { title:'Frontend Developer', skills:['javascript','react','html','css','git'], why:'You can turn ideas into accessible experiences people use every day.' },
  { title:'AI / ML Engineer', skills:['python','statistics','machine learning','sql','git'], why:'Your technical curiosity suits building intelligent products.' },
  { title:'UX Researcher', skills:['research','communication','figma','analytics','empathy'], why:'You are well positioned to understand people and improve products.' }
];
const words = (s='') => s.toLowerCase().split(/[,\n; ]+/).filter(Boolean);
const matched = (need, have) => need.filter(s => have.some(h => h.includes(s) || s.includes(h)));
app.get('/api/health', (_,res)=>res.json({status:'ok'}));
app.post('/api/auth/register', async (req,res) => { try { const {name,email,password}=req.body; if(!name||!email||String(password).length<8) return res.status(400).json({message:'Name, email, and an 8+ character password are required.'}); const user=await User.create({name,email,passwordHash:await bcrypt.hash(password,12)}); res.status(201).json({token:signUser(user),user:{id:user._id,name:user.name,email:user.email}}); } catch { res.status(409).json({message:'That email is already registered.'}); } });
app.post('/api/auth/login', async (req,res) => { const user=await User.findOne({email:String(req.body.email||'').toLowerCase()}); if(!user || !await bcrypt.compare(req.body.password||'',user.passwordHash)) return res.status(401).json({message:'Invalid email or password.'}); res.json({token:signUser(user),user:{id:user._id,name:user.name,email:user.email}}); });
app.post('/api/career/recommend',(req,res)=>{const have=words(`${req.body.skills||''} ${req.body.interests||''}`); const recommendations=careers.map(c=>{const found=matched(c.skills,have);return {...c,matched:found,score:Math.max(48,Math.round(45+found.length/c.skills.length*50))}}).sort((a,b)=>b.score-a.score).slice(0,3);res.json({recommendations})});
app.post('/api/resume/analyze',(req,res)=>{const text=String(req.body.text||'');const rules=[['contact details',/@|\+?\d{8,}/],['skills section',/skills?/i],['project evidence',/project|built|developed/i],['education',/education|university|college|degree/i],['impact metrics',/\d+%|\d+ users|\d+ students/i]];const present=rules.filter(([,r])=>r.test(text)).map(([n])=>n);const missing=rules.filter(([,r])=>!r.test(text)).map(([n])=>n);res.json({score:Math.min(96,38+present.length*12),present,missing,feedback:missing.length?`Add ${missing.slice(0,2).join(' and ')} to make your achievements easier to verify.`:'Strong foundation. Tighten every bullet with action, context, and measurable impact.'})});
app.post('/api/skills/gap',(req,res)=>{const target=careers.find(c=>c.title===req.body.target)||careers[0];const found=matched(target.skills,words(req.body.skills));const missing=target.skills.filter(s=>!found.includes(s));res.json({target:target.title,match:Math.round(found.length/target.skills.length*100),matched:found,missing,nextStep:missing[0]?`Start with ${missing[0]}; practise it through one small public project.`:'You cover the core skills. Focus next on portfolio evidence and applications.'})});
app.post('/api/roadmap/generate',(req,res)=>{const target=careers.find(c=>c.title===req.body.target)||careers[0];res.json({weeks:[{week:'Weeks 1–2',focus:target.skills.slice(0,2),outcome:'Complete guided fundamentals and notes.'},{week:'Weeks 3–4',focus:target.skills.slice(2,4),outcome:'Build two focused practice exercises.'},{week:'Weeks 5–6',focus:[target.skills[4]||'portfolio','portfolio'],outcome:'Publish one end-to-end project and update resume.'},{week:'Weeks 7–8',focus:['interview practice','applications'],outcome:'Do 3 mock interviews and submit 10 tailored applications.'}]})});
app.post('/api/interview/evaluate',(req,res)=>{const a=String(req.body.answer||'');const example=/example|project|when i|built|team/i.test(a), result=/result|improved|increased|%|learned/i.test(a);res.json({score:45+(example?25:0)+(result?20:0),feedback:`${example?'Good: you grounded your answer in an example.':'Add a specific example from school, work, or a project.'} ${result?'You also described an outcome.':'Finish with a measurable result or what you learned.'}`,nextQuestion:'Tell me about a time you solved a difficult problem.'})});
app.get('/api/opportunities',(_,res)=>res.json({opportunities:[{type:'Scholarship',title:'STEM Access Grant',location:'India · Remote application',fit:'Profile match: 91%',deadline:'Demo listing — verify before applying'},{type:'Internship',title:'Junior Data Intern',location:'Remote',fit:'Profile match: 84%',deadline:'Demo listing — verify before applying'},{type:'Scholarship',title:'Women in Technology Bursary',location:'India',fit:'Profile match: 78%',deadline:'Demo listing — verify before applying'}]}));
connectDatabase(process.env.MONGODB_URI).catch(error => console.error('Database connection failed:', error.message)).finally(()=>app.listen(process.env.PORT||4000,()=>console.log('LearnBridge API running')));
